# Generated by Django 2.0.8 on 2018-08-23 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee_degrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree_Acronym', models.CharField(blank=True, max_length=100)),
                ('Degree_Name', models.CharField(blank=True, max_length=200)),
                ('Institution_Name', models.CharField(blank=True, max_length=100)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('Start_date', models.CharField(blank=True, max_length=20, null=True)),
                ('End_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employment_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Job_Period', models.CharField(blank=True, max_length=50, null=True)),
                ('Job_Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Achievements', models.CharField(blank=True, max_length=200, null=True)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Job_Level', models.CharField(blank=True, max_length=25, null=True)),
                ('Job_Step', models.CharField(max_length=50)),
                ('Start_date', models.CharField(blank=True, max_length=20, null=True)),
                ('End_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='internship_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_Internship', models.CharField(blank=True, max_length=50, null=True)),
                ('Area_Assigned', models.CharField(blank=True, max_length=50, null=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Supervisor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Start_date', models.CharField(blank=True, max_length=20, null=True)),
                ('Stop_date', models.CharField(blank=True, max_length=20, null=True)),
                ('Paid_Period', models.CharField(blank=True, max_length=50, null=True)),
                ('Stipend_cost_per_month', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('Accomodation_cost_per_month', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('Air_Fare', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('Comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='past_employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Number', models.CharField(blank=True, max_length=200)),
                ('Title', models.CharField(blank=True, max_length=20, null=True)),
                ('First_Name', models.CharField(max_length=200, null=True)),
                ('Middle_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Last_Name', models.CharField(max_length=200, null=True)),
                ('Gender', models.CharField(max_length=20, null=True)),
                ('Date_of_Birth', models.CharField(blank=True, default=django.utils.timezone.now, max_length=20, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_of_Employment', models.CharField(blank=True, max_length=20, null=True)),
                ('Place_of_Recruitment', models.CharField(blank=True, max_length=200, null=True)),
                ('Qualifications_on_Entry', models.TextField(blank=True, null=True)),
                ('Highest_Level_of_Education', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_of_Departure', models.CharField(blank=True, max_length=20, null=True)),
                ('Reason_for_Departure', models.CharField(blank=True, max_length=200, null=True)),
                ('Summary_of_Performance', models.CharField(blank=True, max_length=254, null=True)),
                ('Summary_of_Performance1', models.CharField(blank=True, max_length=254, null=True)),
                ('Summary_of_Performance2', models.CharField(blank=True, max_length=254, null=True)),
                ('Summary_of_Performance3', models.CharField(blank=True, max_length=254, null=True)),
                ('Summary_of_Performance4', models.CharField(blank=True, max_length=254, null=True)),
                ('Special_Comments_Disciplinary_or_Commendation', models.TextField(blank=True, null=True)),
                ('Final_Salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Final_Allowance', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('Job_Status', models.CharField(max_length=100, null=True)),
                ('Verified', models.CharField(blank=True, max_length=50, null=True)),
                ('Verified_By', models.CharField(blank=True, max_length=50, null=True)),
                ('Verified_Date', models.CharField(blank=True, max_length=20, null=True)),
                ('Created_By', models.CharField(blank=True, max_length=50, null=True)),
                ('Created_Date', models.CharField(blank=True, max_length=20, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='personal_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=200)),
                ('Last_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Other_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_of_Birth', models.CharField(blank=True, default=django.utils.timezone.now, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Home_Telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile_Telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('Permanent_Address_Line1', models.CharField(blank=True, max_length=254, null=True)),
                ('Permanent_Address_Line2', models.CharField(blank=True, max_length=254, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Current_Address_Line1', models.CharField(blank=True, max_length=200, null=True)),
                ('Current_Address_Line2', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Documents', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='qualifications_on_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Institution', models.CharField(blank=True, max_length=100, null=True)),
                ('Type_of_Institution', models.CharField(blank=True, max_length=100, null=True)),
                ('Level_Attained', models.CharField(blank=True, max_length=50, null=True)),
                ('Year_Attained', models.CharField(blank=True, max_length=50, null=True)),
                ('Grade', models.CharField(blank=True, max_length=50, null=True)),
                ('Experience', models.CharField(blank=True, max_length=200, null=True)),
                ('InternID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.personal_information')),
            ],
        ),
        migrations.AddField(
            model_name='internship_history',
            name='InternID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.personal_information'),
        ),
        migrations.AddField(
            model_name='employment_history',
            name='PastEmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.past_employees'),
        ),
        migrations.AddField(
            model_name='employee_degrees',
            name='PastEmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.past_employees'),
        ),
        migrations.AddField(
            model_name='countries',
            name='PastEmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.past_employees'),
        ),
    ]
