# Generated by Django 2.0.8 on 2018-08-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_employees',
            name='Documents',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
